// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import "../libraries/ProofOfSQL.sol";
import {SafeERC20, IERC20} from "@openzeppelin-contracts-5.2.0/token/ERC20/utils/SafeERC20.sol";

/// @title OnchainQuery
/// @notice Onchain Proof of SQL consumer for the published SXT table
///         `MY_AUDIT_V2_5731EC0BBEB5F7BCAA2E4BAF3179A7A4C59C2552.STAKERS`. Submits a SELECT against SXT's QueryRouter
///         and emits the verified result in `queryCallback`.
///
/// Lifecycle:
///   1. Caller approves this contract for >=100 SXT (ERC-20).
///   2. `query()` pulls the payment, increments QueryRouter's allowance,
///      and dispatches the request with this contract as the callback.
///   3. The SXT executor runs the SQL, generates a Proof of SQL receipt,
///      and the QueryRouter validates the receipt against the on-chain
///      Verifier in ~150K gas before invoking `queryCallback`.
///   4. `queryCallback` enforces sender == executor + queryId provenance,
///      decodes the typed result columns, and emits one event per row.
///
/// QUERY_PLAN was generated by `commitments_v1_evmProofPlan` for:
///   SELECT STAKER FROM MY_AUDIT_V2_5731EC0BBEB5F7BCAA2E4BAF3179A7A4C59C2552.STAKERS WHERE STAKER = '0x45c56e138881fd3ff46359ba1826d5fc6fccaedc'
/// against SXT chain state hash 0x378f48ab3d5e4ae6123fc8d5f8418a075b75e29647c4c82650f8a0355a7eef63.
///
/// Generated from `templates/OnchainQuery.sol.template` by
/// `examples/scripts/render-onchain-query.mjs`. Re-render after any
/// change to the published table or the SELECT projection.
contract OnchainQuery {
    using SafeERC20 for IERC20;

    /// @dev EVM-encoded Proof of SQL plan. Encodes the table reference and
    ///      any literal predicates from the SQL. Regenerate via
    ///      render-onchain-query.mjs if either the table or the SQL changes.
    bytes public constant QUERY_PLAN = hex"0000000000000001000000000000003c4d595f41554449545f56325f353733314543304242454235463742434141324534424146333137394137413443353943323535322e5354414b4552530000000000000001000000000000000000000000000000065354414b455200000007000000000000000100000000000000065354414b45520000000800000002000000000000000000000000000000010000000000000000000000020000000000000000000000000000000100000007000000000000002a3078343563353665313338383831666433666634363335396261313832366435666336666363616564630000000000000001000000000000000000000000";

    /// @dev Tracks queries this contract has dispatched so the callback can
    ///      verify provenance.
    mapping(bytes32 => bool) public pendingQueries;

    /// @dev Emitted once per row returned by the verified query. Column
    ///      types match the projected SELECT columns.
    event QueryRow(string staker);

    /// @dev Emitted when the verified query returned zero rows.
    event QueryEmpty(bytes32 queryId);

    error UnauthorizedCaller();

    /// @notice Submit the proven query. Caller must have approved this
    ///         contract to spend at least 100 SXT (ERC-20).
    function query() external {
        IQueryRouter.Query memory q = IQueryRouter.Query({
            innerQuery: QUERY_PLAN,
            parameters: ParamsBuilder.serializeParamArray(new bytes[](0)),
            version: VERSION,
            metadata: ""
        });

        IQueryRouter.Callback memory cb = IQueryRouter.Callback({
            callbackContract: address(this),
            selector: OnchainQuery.queryCallback.selector,
            gasLimit: 120000,
            maxGasPrice: 10 gwei,
            callbackData: ""
        });

        uint256 paymentAmount = 100 ether; // 100 SXT (18 decimals)
        IQueryRouter.Payment memory payment = IQueryRouter.Payment({
            paymentAmount: paymentAmount,
            refundTo: msg.sender,
            timeout: uint64(block.timestamp + 1 hours)
        });

        IERC20(SXT).safeTransferFrom(msg.sender, address(this), paymentAmount);
        IERC20(SXT).safeIncreaseAllowance(QUERY_ROUTER, paymentAmount);

        bytes32 queryId = IQueryRouter(QUERY_ROUTER).requestQuery(q, cb, payment);
        pendingQueries[queryId] = true;
    }

    /// @notice Called by the SXT QueryRouter executor with the verified
    ///         query result. Asserts caller == executor and the queryId is
    ///         one this contract dispatched.
    function queryCallback(bytes32 queryId, bytes calldata queryResult, bytes calldata /* callbackData */ ) external {
        if (msg.sender != QUERY_ROUTER_EXECUTOR || !pendingQueries[queryId]) {
            revert UnauthorizedCaller();
        }
        delete pendingQueries[queryId];

        (, ProofOfSqlTable.Table memory tableResult) = ProofOfSqlTable.__deserializeFromBytes(queryResult);

        string[] memory _col0 = ProofOfSqlTable.readVarCharColumn(tableResult, 0);

        uint256 nRows = _col0.length;
        if (nRows == 0) {
            emit QueryEmpty(queryId);
            return;
        }
        for (uint256 i = 0; i < nRows; ++i) {
            emit QueryRow(_col0[i]);
        }
    }
}
