// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import "../libraries/ProofOfSQL.sol";
import {SafeERC20, IERC20} from "@openzeppelin-contracts-5.2.0/token/ERC20/utils/SafeERC20.sol";

/// @title StakersQuery
/// @notice Onchain Proof of SQL consumer for the published SXT table
///         `MY_AUDIT_V2_5731EC0BBEB5F7BCAA2E4BAF3179A7A4C59C2552.STAKERS`.
///         Proves whether a specific staker address is a member of the table
///         and emits the verified result.
///
/// Lifecycle:
///   1. Caller approves this contract for >= 100 SXT (ERC-20).
///   2. `query()` pulls the payment, increments QueryRouter's allowance,
///      and dispatches the request with this contract as the callback.
///   3. The SXT executor runs the SQL, generates a Proof of SQL receipt,
///      and the QueryRouter validates the receipt against the on-chain
///      Verifier in ~150K gas before invoking `queryCallback`.
///   4. `queryCallback` enforces sender == executor + queryId provenance,
///      decodes the VARCHAR column, and emits `MembershipProven` for each
///      returned row (or `MembershipNotFound` if the result set is empty).
///
/// QUERY_PLAN was generated by `commitments_v1_evmProofPlan` for:
///   SELECT STAKER FROM MY_AUDIT_V2_5731EC0BBEB5F7BCAA2E4BAF3179A7A4C59C2552.STAKERS
///     WHERE STAKER = '0x6de6e901bbefd26a9888798a25e4a49309d04ca9'
/// against SXT chain state hash
///   0xd9649eadffdbef42c991fef7938001d4e8e2d9fa30f9dfe6805ad6a04f6b1936.
///
/// Source artifact: examples/data/proof-plans/point-lookup.json.
/// To regenerate the plan after a republish: `node save-proof-plans.mjs`,
/// then update the QUERY_PLAN constant below.
contract StakersQuery {
    using SafeERC20 for IERC20;

    /// @dev EVM-encoded Proof of SQL plan binding the table reference and
    ///      the parameterized address. Opaque bytes; verified by the
    ///      QueryRouter executor and the on-chain Verifier.
    bytes public constant QUERY_PLAN = hex"0000000000000001000000000000003c4d595f41554449545f56325f353733314543304242454235463742434141324534424146333137394137413443353943323535322e5354414b4552530000000000000001000000000000000000000000000000065354414b455200000007000000000000000100000000000000065354414b45520000000800000002000000000000000000000000000000010000000000000000000000020000000000000000000000000000000100000007000000000000002a3078366465366539303162626566643236613938383837393861323565346134393330396430346361390000000000000001000000000000000000000000";

    /// @dev The staker address the QUERY_PLAN proves membership for. Off-chain
    ///      consumers can read this without parsing the plan bytes.
    address public constant CHECKED_STAKER = 0x6DE6E901Bbefd26a9888798a25E4A49309D04CA9;

    /// @dev Tracks queries this contract dispatched so the callback can
    ///      verify provenance and prevent replay.
    mapping(bytes32 => bool) public pendingQueries;

    /// @notice Emitted from the callback for each row the verified query
    ///         returned. For this point-lookup plan, fires exactly once
    ///         when CHECKED_STAKER is in the table.
    event MembershipProven(string staker);

    /// @notice Emitted when the verified query returned zero rows — the
    ///         CHECKED_STAKER address is provably not in the table.
    event MembershipNotFound(bytes32 queryId);

    error UnauthorizedCaller();

    /// @notice Submit the proven membership query. Caller must have
    ///         approved this contract to spend at least 100 SXT (ERC-20).
    function query() external {
        IQueryRouter.Query memory q = IQueryRouter.Query({
            innerQuery: QUERY_PLAN,
            parameters: ParamsBuilder.serializeParamArray(new bytes[](0)),
            version: VERSION,
            metadata: ""
        });

        IQueryRouter.Callback memory cb = IQueryRouter.Callback({
            callbackContract: address(this),
            selector: StakersQuery.queryCallback.selector,
            gasLimit: 100_000,
            maxGasPrice: 10 gwei,
            callbackData: ""
        });

        uint256 paymentAmount = 100 ether; // 100 SXT (18 decimals)
        IQueryRouter.Payment memory payment = IQueryRouter.Payment({
            paymentAmount: paymentAmount,
            refundTo: msg.sender,
            timeout: uint64(block.timestamp + 1 hours)
        });

        IERC20(SXT).safeTransferFrom(msg.sender, address(this), paymentAmount);
        IERC20(SXT).safeIncreaseAllowance(QUERY_ROUTER, paymentAmount);

        bytes32 queryId = IQueryRouter(QUERY_ROUTER).requestQuery(q, cb, payment);
        pendingQueries[queryId] = true;
    }

    /// @notice Called by the SXT QueryRouter executor with the verified
    ///         query result. Asserts caller == executor and the queryId
    ///         is one this contract dispatched, then decodes the result
    ///         and emits the appropriate event.
    function queryCallback(bytes32 queryId, bytes calldata queryResult, bytes calldata /* callbackData */ ) external {
        if (msg.sender != QUERY_ROUTER_EXECUTOR || !pendingQueries[queryId]) {
            revert UnauthorizedCaller();
        }
        delete pendingQueries[queryId];

        (, ProofOfSqlTable.Table memory tableResult) = ProofOfSqlTable.__deserializeFromBytes(queryResult);
        string[] memory stakers = ProofOfSqlTable.readVarCharColumn(tableResult, 0);

        if (stakers.length == 0) {
            emit MembershipNotFound(queryId);
            return;
        }
        for (uint256 i = 0; i < stakers.length; ++i) {
            emit MembershipProven(stakers[i]);
        }
    }
}
