// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import "../libraries/ProofOfSQL.sol";
import {SafeERC20, IERC20} from "@openzeppelin-contracts-5.2.0/token/ERC20/utils/SafeERC20.sol";

/// @title WalletActivityProver
/// @notice Onchain Proof of SQL consumer for the SXT-indexed table
///         `ETHEREUM.TRANSACTIONS`. Accepts caller-supplied parameter values
///         at query time (one deployed contract serves arbitrary inputs),
///         encodes them via `ParamsBuilder`, and emits the cryptographically
///         verified result in `queryCallback`.
///
/// Lifecycle:
///   1. Caller approves this contract for >=100 SXT (ERC-20).
///   2. `query(...)` encodes the parameter values, pulls the payment,
///      and dispatches the request with this contract as the callback.
///   3. The SXT executor runs the SQL against the committed snapshot,
///      generates a Proof of SQL receipt, and the QueryRouter validates
///      the receipt against the onchain Verifier in ~150K gas before
///      invoking `queryCallback`.
///   4. `queryCallback` enforces sender == executor + queryId provenance,
///      decodes the typed result columns, and emits the input parameters
///      alongside the proven output values so the event log is
///      self-describing on the block explorer.
///
/// QUERY_PLAN was generated by `commitments_v1_evmProofPlan` for:
///   SELECT COUNT(*) FROM ETHEREUM.TRANSACTIONS WHERE FROM_ADDRESS = $1 AND BLOCK_NUMBER >= $2
/// against SXT chain state hash 0xba1ff4614718b914c0c7b7c953abfa4334fc7069a69b2b82367ba25fbba3ef1a.
///
/// Generated from `templates/OnchainQueryParameterized.sol.template` by
/// `examples/scripts/render-onchain-query.mjs`. Re-render after any
/// change to the underlying table catalog or the SELECT projection.
contract WalletActivityProver {
    using SafeERC20 for IERC20;

    /// @dev EVM-encoded Proof of SQL plan with `$1`, `$2`, ... placeholders
    ///      bound at call time. Regenerate via render-onchain-query.mjs if
    ///      the table or SQL shape changes.
    bytes public constant QUERY_PLAN = hex"00000000000000010000000000000015455448455245554d2e5452414e53414354494f4e5300000000000000020000000000000000000000000000000c424c4f434b5f4e554d424552000000050000000000000000000000000000000c46524f4d5f414444524553530000000b00000000000000010000000000000008434f554e54282a2900000003000000090000000800000002000000000000000000000000000000020000000000000000000000000000000100000006000000020000000000000000000000010000000b00000000000000000000000b000000080000000a0000000000000000000000000000000b000000000000000100000005010000000000000000000000000000000000000001000000000100000000000000000000000000000001300000000000000001000000000000000000000000";

    /// @dev Holds the input parameters supplied by the caller so the
    ///      callback can emit them alongside the proven result.
    struct CallbackContext {
        address caller;
        string from_address;
        int64 block_number;
    }
    mapping(bytes32 => CallbackContext) public pendingQueries;

    /// @dev Emitted once per row returned by the verified query. Input
    ///      parameters echo first (for log self-description on BaseScan),
    ///      then the proven output columns.
    event QueryRow(string from_address, int64 block_number, int64 cnt);

    /// @dev Emitted when the verified query returned zero rows.
    event QueryEmpty(bytes32 indexed queryId, string from_address, int64 block_number);

    error UnauthorizedCaller();
    error NoPendingQuery();

    /// @notice Submit the proven query with caller-supplied parameter values.
    ///         Caller must have approved this contract to spend at least
    ///         100 SXT (ERC-20).
    function query(string memory from_address, int64 block_number) external {
        // ── Encode parameters via ParamsBuilder ──────────────────────────
        bytes[] memory paramArr = new bytes[](2);
        paramArr[0] = ParamsBuilder.varCharParam(from_address);
        paramArr[1] = ParamsBuilder.bigIntParam(block_number);

        IQueryRouter.Query memory q = IQueryRouter.Query({
            innerQuery: QUERY_PLAN,
            parameters: ParamsBuilder.serializeParamArray(paramArr),
            version: VERSION,
            metadata: ""
        });

        IQueryRouter.Callback memory cb = IQueryRouter.Callback({
            callbackContract: address(this),
            selector: WalletActivityProver.queryCallback.selector,
            gasLimit: 130000,
            maxGasPrice: 10 gwei,
            callbackData: ""
        });

        uint256 paymentAmount = 100 ether; // 100 SXT (18 decimals)
        IQueryRouter.Payment memory payment = IQueryRouter.Payment({
            paymentAmount: paymentAmount,
            refundTo: msg.sender,
            timeout: uint64(block.timestamp + 1 hours)
        });

        IERC20(SXT).safeTransferFrom(msg.sender, address(this), paymentAmount);
        IERC20(SXT).safeIncreaseAllowance(QUERY_ROUTER, paymentAmount);

        bytes32 queryId = IQueryRouter(QUERY_ROUTER).requestQuery(q, cb, payment);
        pendingQueries[queryId] = CallbackContext({
            caller: msg.sender,
            from_address: from_address,
            block_number: block_number
        });
    }

    /// @notice Called by the SXT QueryRouter executor with the verified
    ///         query result. Asserts caller == executor and the queryId is
    ///         one this contract dispatched.
    function queryCallback(bytes32 queryId, bytes calldata queryResult, bytes calldata /* callbackData */ )
        external
    {
        CallbackContext memory ctx = pendingQueries[queryId];
        if (msg.sender != QUERY_ROUTER_EXECUTOR) revert UnauthorizedCaller();
        if (ctx.caller == address(0)) revert NoPendingQuery();
        delete pendingQueries[queryId];

        (, ProofOfSqlTable.Table memory tableResult) = ProofOfSqlTable.__deserializeFromBytes(queryResult);

        int64[] memory _col0 = ProofOfSqlTable.readBigIntColumn(tableResult, 0);

        uint256 nRows = _col0.length;
        if (nRows == 0) {
            emit QueryEmpty(queryId, ctx.from_address, ctx.block_number);
            return;
        }
        for (uint256 i = 0; i < nRows; ++i) {
            emit QueryRow(ctx.from_address, ctx.block_number, _col0[i]);
        }
    }
}
